<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UnionCouncil;

class UnionCouncilSeeder extends Seeder
{
    public function run()
    {
        $unionCouncils = [
            ['name' => 'Union Council 1', 'tehsil_id' => 1],
            ['name' => 'Union Council 2', 'tehsil_id' => 2],
            ['name' => 'Union Council 3', 'tehsil_id' => 3],
            ['name' => 'Union Council 4', 'tehsil_id' => 4],
            ['name' => 'Union Council 5', 'tehsil_id' => 5],
            ['name' => 'Union Council 6', 'tehsil_id' => 6],
            ['name' => 'Union Council 7', 'tehsil_id' => 7],
            ['name' => 'Union Council 8', 'tehsil_id' => 8],
            ['name' => 'Union Council 9', 'tehsil_id' => 9],
            ['name' => 'Union Council 10', 'tehsil_id' => 10],
            ['name' => 'Union Council 11', 'tehsil_id' => 11],
            ['name' => 'Union Council 12', 'tehsil_id' => 12],
            ['name' => 'Union Council 13', 'tehsil_id' => 13],
            ['name' => 'Union Council 14', 'tehsil_id' => 14],
            ['name' => 'Union Council 15', 'tehsil_id' => 15],
            ['name' => 'Union Council 16', 'tehsil_id' => 16],
            ['name' => 'Union Council 17', 'tehsil_id' => 17],
            ['name' => 'Union Council 18', 'tehsil_id' => 18],
            ['name' => 'Union Council 19', 'tehsil_id' => 19],
            ['name' => 'Union Council 20', 'tehsil_id' => 20],
            ['name' => 'Union Council 21', 'tehsil_id' => 21],
            ['name' => 'Union Council 22', 'tehsil_id' => 22],
            ['name' => 'Union Council 23', 'tehsil_id' => 23],
            ['name' => 'Union Council 24', 'tehsil_id' => 24],
            ['name' => 'Union Council 25', 'tehsil_id' => 25],
            ['name' => 'Union Council 26', 'tehsil_id' => 26],
            ['name' => 'Union Council 27', 'tehsil_id' => 27],
            ['name' => 'Union Council 28', 'tehsil_id' => 28],
            ['name' => 'Union Council 29', 'tehsil_id' => 29],
            ['name' => 'Union Council 30', 'tehsil_id' => 30],
            ['name' => 'Union Council 31', 'tehsil_id' => 31],
            ['name' => 'Union Council 32', 'tehsil_id' => 32],
            ['name' => 'Union Council 33', 'tehsil_id' => 33],
            ['name' => 'Union Council 34', 'tehsil_id' => 34],
            ['name' => 'Union Council 35', 'tehsil_id' => 35],
            ['name' => 'Union Council 36', 'tehsil_id' => 36],
            ['name' => 'Union Council 37', 'tehsil_id' => 37],
            ['name' => 'Union Council 38', 'tehsil_id' => 38],
            ['name' => 'Union Council 39', 'tehsil_id' => 39],
            ['name' => 'Union Council 40', 'tehsil_id' => 40],
            ['name' => 'Union Council 41', 'tehsil_id' => 41],
            ['name' => 'Union Council 42', 'tehsil_id' => 42],
            ['name' => 'Union Council 43', 'tehsil_id' => 43],
            ['name' => 'Union Council 44', 'tehsil_id' => 44],
            ['name' => 'Union Council 45', 'tehsil_id' => 45],
            ['name' => 'Union Council 46', 'tehsil_id' => 46],
            ['name' => 'Union Council 47', 'tehsil_id' => 47],
            ['name' => 'Union Council 48', 'tehsil_id' => 48],
            ['name' => 'Union Council 49', 'tehsil_id' => 49],
            ['name' => 'Union Council 50', 'tehsil_id' => 50],
            ['name' => 'Union Council 51', 'tehsil_id' => 51],
            ['name' => 'Union Council 52', 'tehsil_id' => 52],
            ['name' => 'Union Council 53', 'tehsil_id' => 53],
            ['name' => 'Union Council 54', 'tehsil_id' => 54],
            ['name' => 'Union Council 55', 'tehsil_id' => 55],
            ['name' => 'Union Council 56', 'tehsil_id' => 56],
            ['name' => 'Union Council 57', 'tehsil_id' => 57],
            ['name' => 'Union Council 58', 'tehsil_id' => 58],
            ['name' => 'Union Council 59', 'tehsil_id' => 59],
            ['name' => 'Union Council 60', 'tehsil_id' => 60],
            ['name' => 'Union Council 61', 'tehsil_id' => 61],
            ['name' => 'Union Council 62', 'tehsil_id' => 62],
            ['name' => 'Union Council 63', 'tehsil_id' => 63],
            ['name' => 'Union Council 64', 'tehsil_id' => 64],
            ['name' => 'Union Council 65', 'tehsil_id' => 65],
            ['name' => 'Union Council 66', 'tehsil_id' => 66],
            ['name' => 'Union Council 67', 'tehsil_id' => 67],
            ['name' => 'Union Council 68', 'tehsil_id' => 68],
            ['name' => 'Union Council 69', 'tehsil_id' => 69],
            ['name' => 'Union Council 70', 'tehsil_id' => 70],
            ['name' => 'Union Council 71', 'tehsil_id' => 71],
            ['name' => 'Union Council 72', 'tehsil_id' => 72],
            ['name' => 'Union Council 73', 'tehsil_id' => 73],
            ['name' => 'Union Council 74', 'tehsil_id' => 74],
            ['name' => 'Union Council 75', 'tehsil_id' => 75],
            ['name' => 'Union Council 76', 'tehsil_id' => 76],
            ['name' => 'Union Council 77', 'tehsil_id' => 77],
            ['name' => 'Union Council 78', 'tehsil_id' => 78],
            ['name' => 'Union Council 79', 'tehsil_id' => 79],
            ['name' => 'Union Council 80', 'tehsil_id' => 80],
            ['name' => 'Union Council 81', 'tehsil_id' => 81],
            ['name' => 'Union Council 82', 'tehsil_id' => 82],
            ['name' => 'Union Council 83', 'tehsil_id' => 83],
            ['name' => 'Union Council 84', 'tehsil_id' => 84],
            ['name' => 'Union Council 85', 'tehsil_id' => 85],
            ['name' => 'Union Council 86', 'tehsil_id' => 86],
            ['name' => 'Union Council 87', 'tehsil_id' => 87],
            ['name' => 'Union Council 88', 'tehsil_id' => 88],
            ['name' => 'Union Council 89', 'tehsil_id' => 89],
            ['name' => 'Union Council 90', 'tehsil_id' => 90],
            ['name' => 'Union Council 91', 'tehsil_id' => 91],
            ['name' => 'Union Council 92', 'tehsil_id' => 92],
            ['name' => 'Union Council 93', 'tehsil_id' => 93],
            ['name' => 'Union Council 94', 'tehsil_id' => 94],
            ['name' => 'Union Council 95', 'tehsil_id' => 95],
            ['name' => 'Union Council 96', 'tehsil_id' => 96],
            ['name' => 'Union Council 97', 'tehsil_id' => 97],
            ['name' => 'Union Council 98', 'tehsil_id' => 98],
            ['name' => 'Union Council 99', 'tehsil_id' => 99],
            ['name' => 'Union Council 100', 'tehsil_id' => 100],
        ];

        foreach ($unionCouncils as $uc) {
            UnionCouncil::create($uc);
        }
    }
}
